language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
    - gfortran

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then export FC=/usr/local/bin/gfortran-9             ;fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export FC=/usr/bin/gfortran                     ;fi

script:
  - mkdir build && cd build && cmake .. -DCMAKE_Fortran_COMPILER=$FC && cmake --build . --target install
