language: cpp

os:
  - linux
  - osx

compiler: 
  - gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gfortran
    - gcc
    - g++
    - cmake

before_install:
  # OSX Setup 
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then brew update                                                                               ;fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then brew install gcc                                                                          ;fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then brew link gcc                                                                             ;fi

install:
  # OSX Setup
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then export CMAKE_Fortran_COMPILER=/usr/local/bin/gfortran-7                                   ;fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then export CMAKE_C_COMPILER=/usr/local/bin/gcc-7                                              ;fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then export CMAKE_CXX_COMPILER=/usr/local/bin/g++-7                                            ;fi 
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then export CMAKE_LINKER=clang++                                                               ;fi 
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then export FC=${CMAKE_Fortran_COMPILER}                                                       ;fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then export CC=${CMAKE_C_COMPILER}                                                             ;fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then export CXX=${CMAKE_CXX_COMPILER}                                                          ;fi

  # Linux Setup 
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CXX="/usr/bin/g++"                                                                 ;fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CC="/usr/bin/gcc"                                                                  ;fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export FC="/usr/bin/gfortran"                                                             ;fi

script:
  - mkdir build && cd build && cmake .. && cmake --build . --target install

